on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Setup Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.11'

# this doesn't work.
#      - name: Cache Julia Packages
#        uses: julia-actions/cache@v2

      - name: Install IJulia Jupyter kernel
        shell: bash
        run: julia -e 'using Pkg; Pkg.add("IJulia");'

      - name: Install useful Julia packages
        shell: bash
        run: julia -e 'using Pkg; Pkg.add(filter(x -> x!="", split(read("julia_packages.txt", String), "\n")));'

      - name: Install Quarto extensions for Reveal.js
        shell: bash
        run: |
          quarto add martinomagnifico/quarto-appearance --no-prompt
          quarto add quarto-ext/pointer --no-prompt

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
